import re
import subprocess
from datetime import date, datetime, timedelta, timezone
from flask import session
from flask_login import logout_user
from Advance.extensions import db
from advance_models import Login
from .admin.admin_models import Message
from .setup.setup_models import EmailInternal, EmailNotification, Keyword

def alert_scan(text):

    if not text:
        return []

    keywords = db.session.query(Keyword).all()

    matches = []

    for kw in keywords:
        if re.search(rf"\b{re.escape(kw.keyword)}\b", text, re.IGNORECASE):
            matches.append(kw.keyword)

    if matches:

        subject = "EMERGENCY KEYWORD ALERT"

        body = (
            f"Detected Keywords: {', '.join(matches)}\n\n"
            "Entry Text:\n"
            "----------------------------------------\n"
            f"{text}\n"
            "----------------------------------------\n\n"
            "Email Generated by SQLAdvance"
        )

        alert_send(
            subject=subject,
            body=body
        )

        internal_users = (
            db.session.query(EmailInternal)
            .filter(EmailInternal.alert == "Yes")
            .all()
        )

        if not internal_users:
            return None

        for user in internal_users:
            send_message(
                receiver_id=user.user_id,
                receiver_name=user.fullname,
                subject=subject,
                body=body,
                sender="Keyword Scanner"
            )

    return matches

def alert_send(subject, body):

    recipients = [
        r.user_email
        for r in db.session.query(EmailNotification)
        .filter(EmailNotification.alert == "Yes")
        .all()
    ]

    if not recipients:
        return None

    cmd = [
        "mutt",
        "-s", subject,
        "-c", ",".join(recipients),
        "--",
        recipients[0],
    ]

    return subprocess.run(cmd, input=body, text=True, capture_output=True)

def check_session_timeout():
    timeout_threshold = 240  # minutes

    username = session.get("username")
    if not username:
        return

    login_row = (
        db.session.query(Login)
        .filter(Login.username == username)
        .order_by(Login.logtime.desc())
        .first()
    )

    if not login_row or not login_row.logtime:
        return

    # --- normalize BOTH sides to UTC-aware ---
    current_time = datetime.now(timezone.utc)

    login_time = login_row.logtime

    # if DB returns naive datetime, assume UTC
    if login_time.tzinfo is None:
        login_time = login_time.replace(tzinfo=timezone.utc)

    # if DB returns aware datetime, normalize to UTC
    else:
        login_time = login_time.astimezone(timezone.utc)

    diff_minutes = (current_time - login_time).total_seconds() / 60

    if diff_minutes > timeout_threshold:
        logout_user()
        session.clear()

def emergency_alert(body):

    subject = "Emergency Notification"

    alert_send(
        subject=subject,
        body=body
    )

    internal_users = (
        db.session.query(EmailInternal)
        .filter(EmailInternal.alert == "Yes")
        .all()
    )

    for user in internal_users:
        send_message(
            receiver_id=user.user_id,
            receiver_name=user.fullname,
            subject=subject,
            body=body,
            sender="Emergency Alert"
        )

def get_date_range(request):
    """
    Return start_date and end_date from form,
    defaulting to the last 30 days.
    """

    today = date.today()

    start_date = request.form.get(
        "start_date",
        (today - timedelta(days=30)).isoformat()
    )

    end_date = request.form.get(
        "end_date",
        today.isoformat()
    )

    return start_date, end_date

def maintenance_alert(body):

    subject = "Emergency Situation (Maintenance)"

    alert_send(
        subject=subject,
        body=body
    )

    internal_users = (
        db.session.query(EmailInternal)
        .filter(EmailInternal.property == "Yes")
        .all()
    )

    for user in internal_users:
        send_message(
            receiver_id=user.user_id,
            receiver_name=user.fullname,
            subject=subject,
            body=body,
            sender="Emergency Alert"
        )

def send_message(
        receiver_id,
        receiver_name,
        subject,
        body,
        sender="System",
        sender_id=0):

    note = Message(
        sender=sender,
        sender_id=sender_id,
        receiver=receiver_name,
        receiver_id=receiver_id,
        subject=subject,
        body=body
    )

    db.session.add(note)
    db.session.commit()

    return note

def tech_support(support):

    subject = f"Technical Support Request [{support.rec_id}]  - {support.unit_lname}"

    body = (
        f"Unit:         {support.unit_lname}\n"
        f"Staff:        {support.staff_name}\n"
        f"Email:        {support.staff_email}\n"
        f"Phone:        {support.staff_phone}\n"
        f"Date:         {support.request_date}\n"
        f"Request Type: {support.request_type}\n"
        f"Client:       {support.client_name or 'N/A'}\n\n"
        "Request:\n"
        "----------------------------------------\n"
        f"{support.request_text}\n"
        "----------------------------------------\n\n"
        "Email Generated by SQLAdvance"
    )

    recipients = [
        r.user_email
        for r in db.session.query(EmailNotification)
        .filter(EmailNotification.support == "Yes")
        .all()
    ]

    if not recipients:
        return None

    cmd = [
        "mutt",
        "-s", subject,
        "-c", ",".join(recipients),
        "--",
        recipients[0],
    ]

    internal_users = (
        db.session.query(EmailInternal)
        .filter(EmailInternal.support == "Yes")
        .all()
    )

    for user in internal_users:
        send_message(
            receiver_id=user.user_id,
            receiver_name=user.fullname,
            subject=subject,
            body=body,
            sender="Emergency Alert"
        )

    return subprocess.run(
        cmd,
        input=body,
        text=True,
        capture_output=True
    )

def tech_support_update(support):

    subject = f"Technical Support Request [{support.rec_id}]  - {support.unit_lname}"

    body = (
        f"Unit:         {support.unit_lname}\n"
        f"Staff:        {support.staff_name}\n"
        f"Email:        {support.staff_email}\n"
        f"Phone:        {support.staff_phone}\n"
        f"Date:         {support.request_date}\n"
        f"Request Type: {support.request_type}\n"
        f"Client:       {support.client_name or 'N/A'}\n\n"
        "Request:\n"
        "----------------------------------------\n"
        f"{support.request_text}\n"
        "----------------------------------------\n"
        f"Response from IT Department:\n"
        f"Status:       {support.request_status}\n"
        "Comments:\n"
        f"{support.request_comment}\n"
        "----------------------------------------\n\n"
        "Email Generated by SQLAdvance"
    )

    recipients = [
        r.user_email
        for r in db.session.query(EmailNotification)
        .filter(EmailNotification.support == "Yes")
        .all()
    ]

    if not recipients:
        return None

    cmd = [
        "mutt",
        "-s", subject,
        "-c", ",".join(recipients),
        "--",
        recipients[0],
    ]

    return subprocess.run(
        cmd,
        input=body,
        text=True,
        capture_output=True
    )

def work_order(maint):

    subject = f"Maintenance Request [{maint.rec_id}] - {maint.unit_lname}"

    body = (
        f"Unit:          {maint.unit_lname}\n"
        f"Staff:         {maint.staff_name}\n"
        f"Email:         {maint.staff_email}\n"
        f"Phone:         {maint.staff_phone}\n"
        f"Date:          {maint.request_date}\n"
        f"Request Type:  {maint.request_type}\n"
        f"Address:       {maint.address}\n"
        f"Client:        {maint.client_name or 'N/A'}\n"
        f"Client Phone:  {maint.client_phone}\n"
        f"Ok to Enter:   {maint.client_permission}\n"
        f"Client Avail:  {maint.client_available}\n"
        f"High Risk:     {maint.high_risk}\n"
        f"Safety Issue:  {maint.safety_issue}\n"
        f"Director Auth: {maint.director_approved}\n"
        "Request:\n"
        "----------------------------------------\n"
        f"{maint.request_text}\n"
        "----------------------------------------\n\n"
        "Email Generated by SQLAdvance"
    )

    recipients = [
        r.user_email
        for r in db.session.query(EmailNotification)
        .filter(EmailNotification.property == "Yes")
        .all()
    ]

    if not recipients:
        return None

    cmd = [
        "mutt",
        "-s", subject,
        "-c", ",".join(recipients),
        "--",
        recipients[0],
    ]

    return subprocess.run(
        cmd,
        input=body,
        text=True,
        capture_output=True
    )

def work_order_update(maint):

    subject = f"Maintenance Request Update [{maint.rec_id}] - {maint.unit_lname}"

    body = (
        f"Unit:          {maint.unit_lname}\n"
        f"Staff:         {maint.staff_name}\n"
        f"Email:         {maint.staff_email}\n"
        f"Phone:         {maint.staff_phone}\n"
        f"Date:          {maint.request_date}\n"
        f"Request Type:  {maint.request_type}\n"
        f"Address:       {maint.address}\n"
        f"Client:        {maint.client_name or 'N/A'}\n"
        f"Client Phone:  {maint.client_phone}\n"
        f"Ok to Enter:   {maint.client_permission}\n"
        f"Client Avail:  {maint.client_available}\n"
        f"High Risk:     {maint.high_risk}\n"
        f"Safety Issue:  {maint.safety_issue}\n"
        f"Director Auth: {maint.director_approved}\n"
        "Request:\n"
        "----------------------------------------\n"
        f"{maint.request_text}\n"
        "----------------------------------------\n"
        f"Response from Property Management:\n"
        f"Cost Center:   {maint.cost_center}\n"
        f"Assigned To:   {maint.assigned_to}\n"
        f"Status:        {maint.request_status}\n"
        "Comments:\n"
        f"{maint.request_comment}\n"
        "----------------------------------------\n\n"
        "Email Generated by SQLAdvance"
    )

    recipients = [
        r.user_email
        for r in db.session.query(EmailNotification)
        .filter(EmailNotification.property == "Yes")
        .all()
    ]

    if not recipients:
        return None

    cmd = [
        "mutt",
        "-s", subject,
        "-c", ",".join(recipients),
        "--",
        recipients[0],
    ]

    return subprocess.run(
        cmd,
        input=body,
        text=True,
        capture_output=True
    )

