BOOLEAN = [
    "",
    "Yes",
    "No",
    "Unknown",
]

SEX = [
    "Male",
    "Female",
    "Unknown",
]

GENDER = [
    "Cisgender",
    "Lesbian",
    "Gay",
    "Bisexual",
    "Transgender",
    "Queer / Questioning",
    "Intersex",
    "Asexual / Ally",
    "Non-Binary",
    "Unknown",
]

ORIENTATION = [
    "Straight",
    "Lesbian or Gay",
    "Bisexual",
    "Pansexual / Queer / Other",
    "Asexual",
    "Questioning",
    "Unknown",
]

RACE = [
    "White",
    "Black",
    "Asian",
    "American Indian / Alaska Native",
    "Native Hawaiian / Other Pacific Islander",
    "Other",
    "Unknown",
]

RACE_DETAIL = [
    "African-American", 
    "Afro-Caribbean", 
    "African Continent", 
    "Other Black", 
    "Not Applicable", 
    "Unknown",
]

ASIAN_DETAIL = [
    "Asian Indian", 
    "Bangladeshi", 
    "Burmese", 
    "Cambodian", 
    "Chinese",
    "Filipino", 
    "Hmong", 
    "Indonesian", 
    "Japanese", 
    "Korean",
    "Laotian", 
    "Malaysian", 
    "Nepalese", 
    "Pakistani", 
    "Sri Lankan",
    "Taiwanese", 
    "Thai", 
    "Tibetan", 
    "Vietnamese", 
    "Not Applicable",
    "Unknown",
]

PACIFIC_DETAIL = [
    "Chamorro", 
    "Fijian", 
    "Guamanian", 
    "Native Hawaiian", 
    "Samoan", 
    "Tongan",
    "Other Pacific Islander", 
    "Not Applicable", 
    "Unknown or Missing",
]

ETHNICITY = [
    "Non-Hispanic/Non-Latino", 
    "Hispanic/Latino", 
    "Unknown", 
]

ETHNICITY_DETAIL = [
    "Central American",
    "Cuban",
    "Dominican",
    "Mexican",
    "Other Caribbean",
    "Puerto Rican",
    "South American",
    "Spaniard",
    "Other",
    "Not Applicable",
    "Unknown",
]

HOUSEHOLD = [
    "Lives Alone",
    "Lives With Child, Stepchild, Foster Child or Grandchild",
    "Lives With Parent",
    "Lives With Sibling",
    "Lives With Spouse or Domestic Partner",
    "Lives With Other Relatives Not Specified Above",
    "Lives With Foster Parent",
    "Lives With Other People Unrelated To Client",
    "Unknown",
    "Not In Private Residence.",
]

PARENT = [
    "No Children",
    "Client Has Children Over 18",
    "Has Minor Children, In Client's Custody",
    "Has Minor Children, NOT In Client's Custody",
    "Expectant Parent",
    "Unknown",
]

LANGUAGE = [
    "African Language",
    "Albanian",
    "Amharic",
    "Arabic",
    "Armenian",
    "Bengali",
    "Cajun",
    "Cantonese",
    "Chinese",
    "Croatian",
    "Czech",
    "Danish",
    "Dutch",
    "English",
    "Finnish",
    "Formosan",
    "French",
    "French/Haitian Creole",
    "Fujianese",
    "German",
    "Greek",
    "Gujarathi",
    "Hebrew",
    "Hindi",
    "Hungarian",
    "Ilocano",
    "Italian",
    "Japanese",
    "Korean",
    "Kru",
    "Lithuanian",
    "Malayalam",
    "Mandarin",
    "Miao",
    "Mon-Khmer",
    "Navaho",
    "Norwegian",
    "Other",
    "Other Asian",
    "Other Chinese",
    "Other Indic [e.g.,Sindhi)",
    "Other Indo-European",
    "Panjabi",
    "Persian",
    "Polish",
    "Portuguese",
    "Portuguese/Creole",
    "Rumanian",
    "Russian",
    "Samoan",
    "Serbian",
    "Sign Language",
    "Slovak",
    "Spanish",
    "Spanish/Spanish Creole",
    "Swedish",
    "Syrian",
    "Tagalog",
    "Thai",
    "Turkish",
    "Ukrainian",
    "Urdu",
    "Vietnamese",
    "Yiddish",
    "Pennsylvania Dutch/Other Germanic",
    "Unknown",
]

MARITAL = [
    "Single",
    "Married",
    "Divorced",
    "Widowed",
    "Separated",
    "Unknown",
]

RELIGION = [
    "Agnostic",
    "Atheist",
    "Baptist",
    "Born Again",
    "Buddhist",
    "Catholic",
    "Christian",
    "Greek Orthodox",
    "Hindu",
    "Jewish",
    "Lutheran",
    "Methodist",
    "Muslim",
    "None",
    "Other",
    "Protestant",
    "Unknown",
]
