from Advance.extensions import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class MPI(UserMixin, db.Model):
        client_id         = db.Column(db.Integer, primary_key=True)
        fname             = db.Column(db.String(30), nullable=False)
        lname             = db.Column(db.String(30), nullable=False)
        dob               = db.Column(db.DateTime)
        ssn               = db.Column(db.String(11))
        medicaid          = db.Column(db.String(8))

class Accounts(UserMixin, db.Model):
        rec_id            = db.Column(db.Integer, primary_key=True)
        client_id         = db.Column(db.Integer)
        unit_id           = db.Column(db.Integer)
        unit_lname        = db.Column(db.String(255))
        track_id          = db.Column(db.Integer)
        staff_id          = db.Column(db.Integer)
        staff_name        = db.Column(db.String(255))
        start_date        = db.Column(db.DateTime)
        end_date          = db.Column(db.DateTime, nullable=True)
        account_id        = db.Column(db.String(64))
        icd_10            = db.Column(db.String(255))
        physician_name    = db.Column(db.String(255))
        physician_licence = db.Column(db.String(80))
        physician_npi     = db.Column(db.String(80))
        time_insert       = db.Column(db.DateTime)
        time_update       = db.Column(db.DateTime)
        update_by         = db.Column(db.String(255))

class Demographics(UserMixin, db.Model):
        rec_id            = db.Column(db.Integer, primary_key=True)
        client_id         = db.Column(db.Integer)
        unit_id           = db.Column(db.Integer)
        unit_lname        = db.Column(db.String(255))
        track_id          = db.Column(db.Integer)
        alias             = db.Column(db.String)
        allergy           = db.Column(db.String)
        address           = db.Column(db.String(255))
        apartment         = db.Column(db.String(255))
        city              = db.Column(db.String(255))
        state             = db.Column(db.String(80))
        post_code         = db.Column(db.String(80))
        phone             = db.Column(db.String(80))
        phone_mobile      = db.Column(db.String(80))
        phone_other       = db.Column(db.String(80))
        sex_birth         = db.Column(db.String(80))
        sex_gender        = db.Column(db.String(80))
        sex_orientation   = db.Column(db.String(80))
        race              = db.Column(db.String(80))
        race_detail       = db.Column(db.String(80))
        asian_detail      = db.Column(db.String(80))
        pacific_detail    = db.Column(db.String(80))
        ethnicity         = db.Column(db.String(80))
        ethnicity_detail  = db.Column(db.String(80))
        place_of_birth    = db.Column(db.String(80))
        citizen           = db.Column(db.String(80))
        veteran           = db.Column(db.String(80))
        language_spoken   = db.Column(db.String(80))
        religion          = db.Column(db.String(80))
        marital_status    = db.Column(db.String(80))
        parental_status   = db.Column(db.String(80))
        household         = db.Column(db.String(80))
        staff_id          = db.Column(db.Integer)
        staff_name        = db.Column(db.String(255))
        time_insert       = db.Column(db.DateTime(timezone=True), server_default=func.now())
        time_update       = db.Column(db.DateTime)
        update_by         = db.Column(db.String)

class Diagnosis(UserMixin, db.Model):
        rec_id            = db.Column(db.Integer, primary_key=True)
        client_id         = db.Column(db.Integer)
        unit_id           = db.Column(db.Integer)
        unit_lname        = db.Column(db.String(255))
        track_id          = db.Column(db.Integer)
        staff_id          = db.Column(db.Integer)
        staff_name        = db.Column(db.String(255))
        start_date        = db.Column(db.DateTime)
        end_date          = db.Column(db.DateTime, nullable=True)
        dsm5              = db.Column(db.String(255))
        icd10             = db.Column(db.String(255))
        notebody          = db.Column(db.String)

class Diagnosis_DSM5(UserMixin, db.Model):
        rec_id            = db.Column(db.Integer, primary_key=True)
        dsm5              = db.Column(db.String(255))

class Diagnosis_ICD10(UserMixin, db.Model):
        rec_id            = db.Column(db.Integer, primary_key=True)
        icd10             = db.Column(db.String(255))

class Entitlements(UserMixin, db.Model):
        rec_id            = db.Column(db.Integer, primary_key=True)
        client_id         = db.Column(db.Integer)
        unit_id           = db.Column(db.Integer)
        unit_lname        = db.Column(db.String(255))
        track_id          = db.Column(db.Integer)
        social_security   = db.Column(db.String(255))
        ssi               = db.Column(db.String(80))
        ssd               = db.Column(db.String(80))
        medicaid          = db.Column(db.String(80))
        managed_care      = db.Column(db.String(80))
        medicare          = db.Column(db.String(80))
        medicare_id       = db.Column(db.String(80))
        snap              = db.Column(db.String(80))
        snap_id           = db.Column(db.String(80))
        snap_amt          = db.Column(db.String(80))
        public_assistance = db.Column(db.String(255))
        public_amount     = db.Column(db.String(255))
        wages             = db.Column(db.String(80))
        insurance         = db.Column(db.String(80))
        insurance_carrier = db.Column(db.String(255))
        insurance_id      = db.Column(db.String(80))
        alimony           = db.Column(db.String(80))
        pension           = db.Column(db.String(80))
        unemployment      = db.Column(db.String(80))
        workers_comp      = db.Column(db.String(80))
        retirement_income = db.Column(db.String(255))
        child_support     = db.Column(db.String(80))
        other_income      = db.Column(db.String(80))
        wic               = db.Column(db.String(80))
        tanf              = db.Column(db.String(80))
        section_8         = db.Column(db.String(80))
        other_non_cash    = db.Column(db.String(80))
        va_disability     = db.Column(db.String(80))
        va_medical        = db.Column(db.String(80))
        staff_id          = db.Column(db.Integer)
        staff_name        = db.Column(db.String(255))
        time_insert       = db.Column(db.DateTime(timezone=True), server_default=func.now())
        time_update       = db.Column(db.DateTime)
        update_by         = db.Column(db.String)

class Inpatient(UserMixin, db.Model):
        rec_id            = db.Column(db.Integer, primary_key=True)
        client_id         = db.Column(db.Integer)
        client            = db.Column(db.String)
        unit_id           = db.Column(db.Integer)
        unit_lname        = db.Column(db.String(255))
        track_id          = db.Column(db.Integer)
        staff_id          = db.Column(db.Integer)
        staff_name        = db.Column(db.String(255))
        start_date        = db.Column(db.DateTime)
        end_date          = db.Column(db.DateTime, nullable=True)
        visit_date        = db.Column(db.DateTime)
        hospital          = db.Column(db.String(255))
        address           = db.Column(db.String(255))
        hospital_type     = db.Column(db.String(80))
        staff_member      = db.Column(db.String(255))
        staff_shift       = db.Column(db.String(255))
        staff_time        = db.Column(db.String(80))
        voluntary         = db.Column(db.String(3))
        eob               = db.Column(db.String(3))
        state_hospital    = db.Column(db.String(3))
        outcome           = db.Column(db.String(255))
        comment_text      = db.Column(db.String)
        visit_reason      = db.Column(db.String(255))
        admit_date        = db.Column(db.DateTime)
        age               = db.Column(db.String(255))
        sex               = db.Column(db.String(255))
        diagnosis         = db.Column(db.String(255))
        escort_type       = db.Column(db.String(255))
        transport_type    = db.Column(db.String(255))
        complaint         = db.Column(db.String(80))
        time_update       = db.Column(db.DateTime)
        update_by         = db.Column(db.String(255))
        audit_trail       = db.Column(db.String)

class Functional(UserMixin, db.Model):
        rec_id            = db.Column(db.Integer, primary_key=True)
        client_id         = db.Column(db.Integer)
        unit_id           = db.Column(db.Integer)
        unit_lname        = db.Column(db.String(255))
        track_id          = db.Column(db.Integer)
        staff_id          = db.Column(db.Integer)
        staff_name        = db.Column(db.String(255))
        start_date        = db.Column(db.DateTime)
        end_date          = db.Column(db.DateTime, nullable=True)
        skill_level       = db.Column(db.String(80))
        skill_area        = db.Column(db.String(255))
        skill_text        = db.Column(db.String)
        time_in           = db.Column(db.DateTime)

class FunctionalSkills(UserMixin, db.Model):
        rec_id            = db.Column(db.Integer, primary_key=True)
        medicaid_id       = db.Column(db.Integer)
        skill_area        = db.Column(db.String(255))

class Placement(UserMixin, db.Model):
        rec_id            = db.Column(db.Integer, primary_key=True)
        client_id         = db.Column(db.Integer)
        staff_id          = db.Column(db.Integer)
        staff_name        = db.Column(db.String(255))
        unit_id           = db.Column(db.Integer)
        unit_lname        = db.Column(db.String(255))
        track_id          = db.Column(db.Integer)
        address           = db.Column(db.String(255))
        start_date        = db.Column(db.DateTime)
        end_date          = db.Column(db.DateTime, nullable=True)
        airs              = db.Column(db.String(255))
        bip               = db.Column(db.String(24))
        hud               = db.Column(db.String(16))
        input             = db.Column(db.DateTime, nullable=True)
        update            = db.Column(db.DateTime)
        update_by         = db.Column(db.String(255))
        destination       = db.Column(db.String(255))

class ProgressNote(UserMixin, db.Model):
        rec_id            = db.Column(db.Integer, primary_key=True)
        client_id         = db.Column(db.Integer)
        chart             = db.Column(db.String(80))
        unit_id           = db.Column(db.Integer)
        unit_lname        = db.Column(db.String(255))
        track_id          = db.Column(db.Integer)
        staff_id          = db.Column(db.Integer)
        staff_name        = db.Column(db.String(255))
        plan_id           = db.Column(db.Integer)
        goal              = db.Column(db.String(255))
        notedate          = db.Column(db.DateTime)
        notebody          = db.Column(db.String)
        medicaid          = db.Column(db.Integer)
        acronym           = db.Column(db.String(24))
        duration          = db.Column(db.String(80))
        mood_affect       = db.Column(db.String(255))
        thought_process   = db.Column(db.String(255))
        motor_activity    = db.Column(db.String(255))
        behavior          = db.Column(db.String(255))
        medical_condition = db.Column(db.String(255))
        substance_use     = db.Column(db.String(255))
        esof_name         = db.Column(db.String(255))
        esof_date         = db.Column(db.DateTime)
        esof_super_name   = db.Column(db.String(255))
        esof_super_date   = db.Column(db.DateTime)

class SupportPlan(UserMixin, db.Model):
        rec_id              = db.Column(db.Integer, primary_key=True)
        client_id           = db.Column(db.Integer)
        client_name         = db.Column(db.String(255))
        chart_id            = db.Column(db.String(80))
        unit_id             = db.Column(db.Integer)
        unit_lname          = db.Column(db.String(255))
        track_id            = db.Column(db.Integer)
        staff_id            = db.Column(db.Integer)
        staff_name          = db.Column(db.String(255))
        start_date          = db.Column(db.DateTime, nullable=False)
        end_date            = db.Column(db.DateTime, nullable=False)
        caseworker          = db.Column(db.String(80))
        backup              = db.Column(db.String(80))
        supervisor          = db.Column(db.String(80))
        diagnosis           = db.Column(db.String(80))
        needs_selfcare      = db.Column(db.String(80))
        needs_skills        = db.Column(db.String(80))
        needs_support       = db.Column(db.String(80))
        needs_adl           = db.Column(db.String(80))
        needs_focus         = db.Column(db.String(80))
        rights_grievances   = db.Column(db.String(80))
        rights_date         = db.Column(db.DateTime)
        goal_one            = db.Column(db.Integer, default=1)
        goal_one_id         = db.Column(db.String(80))
        goal_one_header     = db.Column(db.String)
        goal_one_medicaid   = db.Column(db.Integer)
        goal_one_acronym    = db.Column(db.String(8))
        goal_one_level      = db.Column(db.String(64))
        goal_one_code       = db.Column(db.Integer)
        goal_one_status     = db.Column(db.String(24))
        goal_one_object     = db.Column(db.String(80))
        goal_one_service    = db.Column(db.String)
        goal_one_eval       = db.Column(db.String)
        goal_one_date       = db.Column(db.DateTime)
        goal_two            = db.Column(db.Integer, default=2)
        goal_two_id         = db.Column(db.String(80))
        goal_two_header     = db.Column(db.String)
        goal_two_medicaid   = db.Column(db.Integer)
        goal_two_acronym    = db.Column(db.String(8))
        goal_two_level      = db.Column(db.String(64))
        goal_two_code       = db.Column(db.Integer)
        goal_two_status     = db.Column(db.String(24))
        goal_two_object     = db.Column(db.String(80))
        goal_two_service    = db.Column(db.String)
        goal_two_eval       = db.Column(db.String)
        goal_two_date       = db.Column(db.DateTime)
        goal_three          = db.Column(db.Integer, default=3)
        goal_three_id       = db.Column(db.String(80))
        goal_three_header   = db.Column(db.String)
        goal_three_medicaid = db.Column(db.Integer)
        goal_three_acronym  = db.Column(db.String(8))
        goal_three_level    = db.Column(db.String(64))
        goal_three_code     = db.Column(db.Integer)
        goal_three_status   = db.Column(db.String(24))
        goal_three_object   = db.Column(db.String(80))
        goal_three_service  = db.Column(db.String)
        goal_three_eval     = db.Column(db.String)
        goal_three_date     = db.Column(db.DateTime)
        goal_four           = db.Column(db.Integer, default=4)
        goal_four_id        = db.Column(db.String(80))
        goal_four_header    = db.Column(db.String)
        goal_four_medicaid  = db.Column(db.Integer)
        goal_four_acronym   = db.Column(db.String(8))
        goal_four_level     = db.Column(db.String(64))
        goal_four_code      = db.Column(db.Integer)
        goal_four_status    = db.Column(db.String(24))
        goal_four_object    = db.Column(db.String(80))
        goal_four_service   = db.Column(db.String)
        goal_four_eval      = db.Column(db.String)
        goal_four_date      = db.Column(db.DateTime)
        esof_id             = db.Column(db.Integer)
        esof_date           = db.Column(db.DateTime)
        esof_name           = db.Column(db.String(255))
        esof_note           = db.Column(db.String(255))
        audit_trail         = db.Column(db.String)
        time_insert         = db.Column(db.DateTime)
        time_update         = db.Column(db.DateTime)
        up_date             = db.Column(db.DateTime)
        up_date_by          = db.Column(db.String(255))

